export enum KnowledgeDomain {
  GENERAL = 'GENERAL',
  CATEGORY = 'CATEGORY',
  CONTACT = 'CONTACT',
  PROJECT = 'PROJECT',
  QUOTE = 'QUOTE',
  SERVICE = 'SERVICE',
  VENDOR = 'VENDOR',
  EXPERT = 'EXPERT',
  SUMMARY = 'SUMMARY',
  FORM = 'FORM RESPONSES',
  UNKNOWN = 'UNKNOWN',
}
